apiVersion: v1
kind: Service
metadata:
  name: java-calculator-web-app
  labels:
    app: java-calculator-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: java-calculator-web-app
    